### ISSUE TITLE
sqlite3.OperationalError: unable to open database file

### ISSUE THREAD

**Issue by Suki-m730026038** [AkariAsai/learning_to_retrieve_reasoning_paths#27]
Hi, when I run quick_start_hotpot.sh it raise error: sqlite3.OperationalError: unable to open database file. But I alreay download all the code, dataset and model.

**Comment by AkariAsai** [comment]
Hi, so sorry for my late response! Could you share the entire error message so that I could see which line is the error happening?

**Comment by mina1987** [comment]
Hey, I get the same error, here is the error message:
`initializing TfidfRetriever...
Traceback (most recent call last):
  File "eval_main.py", line 57, in <module>
    main()
  File "eval_main.py", line 9, in main
    odqa = ODQAEval()
  File "/home/ec2-user/SageMaker/lrrp/learning_to_retrieve_reasoning_paths/eval_odqa.py", line 227, in __init__
    self.args.db_path, self.args.tfidf_path, self.args.use_full_article, self.args.pruning_l)
  File "/home/ec2-user/SageMaker/lrrp/learning_to_retrieve_reasoning_paths/pipeline/tfidf_retriever.py", line 27, in __init__
    self.db = DocDB(db_save_path)
  File "/home/ec2-user/SageMaker/lrrp/learning_to_retrieve_reasoning_paths/retriever/doc_db.py", line 17, in __init__
    self.connection = sqlite3.connect(self.path, check_same_thread=False)
sqlite3.OperationalError: unable to open database file`
